# S-master - APK 构建脚本
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "   S-master - 构建 APK" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan

$ErrorActionPreference = "Continue"

# 设置 JDK
$jdkHome = "C:\Users\H\AppData\Local\Temp\jdk\jdk-17.0.12+7"
$env:JAVA_HOME = $jdkHome
$env:Path = "$jdkHome\bin;$env:PATH"

# 验证 JDK
Write-Host "`n🔍 验证 JDK..." -ForegroundColor Yellow
java -version 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ JDK 不可用" -ForegroundColor Red
    exit 1
}

# 设置 Android SDK
$androidHome = "C:\Users\H\AppData\Local\Android\Sdk"
$env:ANDROID_HOME = $androidHome
$env:ANDROID_SDK_ROOT = $androidHome
$env:Path = "$androidHome\cmdline-tools\latest\bin;$androidHome\platform-tools;$env:Path"

# 安装 SDK 组件
Write-Host "`n📥 安装 Android SDK 组件..." -ForegroundColor Yellow
& "$androidHome\cmdline-tools\latest\bin\sdkmanager.bat" "--sdk_root=$androidHome" "--install" "platforms;android-34" "build-tools;34.0.0" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "⚠️ SDK 安装可能有误，继续尝试构建..." -ForegroundColor Yellow
}

# 切到项目目录
Push-Location $PSScriptRoot

# 创建 local.properties
Write-Host "`n📝 创建 local.properties..." -ForegroundColor Yellow
"## This file is automatically generated by build script.
sdk.dir=$androidHome" | Out-File -FilePath "local.properties" -Encoding ASCII

# 构建 APK
Write-Host "`n🔨 开始构建 APK..." -ForegroundColor Green
echo "y" | .\gradlew assembleDebug --no-daemon 2>&1

if ($LASTEXITCODE -eq 0) {
    Write-Host "`n✅✅✅ 构建成功！" -ForegroundColor Green
    $apkPath = "app\build\outputs\apk\debug"
    if (Test-Path $apkPath) {
        Get-ChildItem $apkPath -Filter "*.apk" | ForEach-Object {
            Write-Host "📱 APK: $($_.FullName) ($(($_.Length/1MB).ToString('0.00')) MB)" -ForegroundColor Green
        }
    }
} else {
    Write-Host "`n❌ 构建失败，查看错误信息" -ForegroundColor Red
}

Pop-Location
